import pygame

#PANTALLA PRINCIPAL

PANTALLA_ANCHO = 1200    
PANTALLA_ALTO = 650

TAMAÑO_PANTALLA = (PANTALLA_ANCHO, PANTALLA_ALTO)

FPS = (60)

TITULO_JUEGO = "Dragon Ball Z Trading Card Game"
ICONO_JUEGO = "assets/img/icons/ALL_stars.png"
FONDO_PANTALLA_PRINCIPAL = "assets/img/forms/img_5.png"
FONDO_PANTALLA_PRINCIPAL_FULL_SCREEN = (0, 0)

MUSICA_PANTALLA_PRINCIPAL = "assets/audio/music/Chala_Head_Chala.ogg"

#RECTANGULOS PANTALLA PRINCIPAL
COORDENADA_RECTANGULO_TITULO = (415, 70, 450, 100)
COORDENADA_RECTANGULO_MENU = (415, 360, 450, 300)

#FUENTES
FUENTE_TITULO = ("assets/fonts/Halimount.otf")
FUENTE_MENU = ("assets/fonts/Saiyan-Sans.ttf")

#COLORES
COLOR_ROJO = (255, 0, 0)
COLOR_NARANJA = (255, 165, 0)

#RECTANGULOS OPCIONES MENU
RECT_JUGAR = pygame.Rect(580, 370, 200, 40)
RECT_OPCIONES = pygame.Rect(580, 430, 200, 40)
RECT_RANKING = pygame.Rect(580, 490, 200, 40)
RECT_SALIR = pygame.Rect(580, 550, 200, 40)


#PANTALLA OPCIONES

FONDO_PANTALLA_OPCIONES = "assets/img/forms/img_6.png"
MUSICA_PANTALLA_OPCIONES = "assets/audio/music/form_options.ogg"

TITULO_OPCIONES = "Menu de Configuraciones"